apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  labels:
    name: gitea
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: gitea
spec:
  chart: gitea
  targetNamespace: gitea
  repo: https://dl.gitea.io/charts/
  version: v3.1.4
---
kind: Service
apiVersion: v1
metadata:
  name: gitea-frontend
  namespace: gitea
spec:
  type: ExternalName
  externalName: gitea-http.gitea.svc.cluster.local
  ports:
    - port: 3000

