apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: This is a basic catalog example that simply
      prints "hello argo!".
    workflows.argoproj.io/maintainer: '@alexec'
    workflows.argoproj.io/tags: example
    workflows.argoproj.io/version: '>= 2.9.0'
  name: hello-world
  namespace: argo
spec:
  serviceAccountName: argo-argo-workflows-workflow-controller
  entrypoint: argosay
  templates:
  - container:
      args:
      - echo
      - hello argo!
      command:
      - /argosay
      image: argoproj/argosay:v2
      name: main
    name: argosay
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: This is a test workflow for building an application and generating an sbom.
    workflows.argoproj.io/maintainer: '@wgodfrey'
    workflows.argoproj.io/tags: SBOM
    workflows.argoproj.io/version: '>= 2.9.0'
  name: release-with-sbom
  namespace: argo
spec:
  serviceAccountName: argo-argo-workflows-workflow-controller
  entrypoint: release-with-sbom      
  volumes:
    - name: rkvst-auth-token
      secret:
        secretName: rkvst-auth-token
    - name: out
      emptyDir: {}
  arguments:
    parameters:
      - name: asset_id
        value: assets/fdd117ca-6bd1-4083-86e3-ec75ead6562f
      - name: build_context
        value: git://github.com/foundriesio/containers.git
      - name: dockerfile
        value: Dockerfile
      - name: sub_context
        value: shellhttpd
      - name: registry
        value: 172.20.0.2:5000
      - name: resultant_image
        value: foundriesio-shellhttpd
      - name: version
        value: v4.1.5
      - name: sbom_version
        value: v4_1_5 
      - name: author
        value: leflambeur
      - name: supplier
        value: foundriesio
  templates:
    - name: builder
      container:
        image: gcr.io/kaniko-project/executor:latest
        args: 
         - "--dockerfile={{workflow.parameters.dockerfile}}"
         - "--context={{workflow.parameters.build_context}}"
         - "--destination={{workflow.parameters.registry}}/{{workflow.parameters.resultant_image}}:{{workflow.parameters.version}}"
         - "--context-sub-path={{workflow.parameters.sub_context}}"
         - "--insecure"
        name: kaniko
    - name: sbom-generation
      container: 
        image: yewnorosen/syft-temp:latest
        args:
         - "registry:{{workflow.parameters.registry}}/{{workflow.parameters.resultant_image}}:{{workflow.parameters.version}}"
         - -o
         - spdx-json
         - "/tmp/{{workflow.parameters.sbom_version}}_sbom.json"
        name: syft
      outputs:
        artifacts:
          - name: sbom
            path: "/tmp/{{workflow.parameters.sbom_version}}_sbom.json"
            s3:
              key: sbom
    - name: sbom-file-preperation
      inputs:
        artifacts:
          - name: sbom
            path: "/tmp/{{workflow.parameters.sbom_version}}_sbom.json"
            s3:
              key: sbom
      container:
        image: alpine:latest
        command: ["/bin/cat"]
        arg:
          - name: "/tmp/{{workflow.parameters.sbom_version}}_sbom.json"
    - name: sbom-output-parsing
      inputs:
        artifacts:
          - name: sbom
            path: "/tmp/{{workflow.parameters.sbom_version}}_sbom.json"
            s3:
              key: sbom
      container:
        image: alpine:latest
        command: ["/bin/echo"]
        arg:
          - "/tmp/{{workflow.parameters.sbom_version}}_sbom.json"
    - name: release-event
      inputs:
        parameters:
          - name: sbom_attrs
          - name: attachments
          - name: latest_sbom
          - name: custom_attrs
          - name: custom_asset_attrs
        artifacts:
          - name: sbom
            path: "/tmp/{{workflow.parameters.sbom_version}}_sbom.json"
            s3:
              key: sbom
      container:
        image: yewnorosen/rkvst-sbom:latest
        args:
          - release
          - "{{ workflow.parameters.asset_id }}"
          - "{{ inputs.parameters.sbom_attrs }}"
          - "{{ inputs.parameters.attachments }}"
          - "{{ inputs.parameters.latest_sbom }}"
          - "{{ inputs.parameters.custom_attrs }}"
          - "{{ inputs.parameters.custom_asset_attrs }}"
        env:
          - name: AUTH_TOKEN  # name of env var
            valueFrom:
              secretKeyRef:
                name: rkvst-auth-token     # name of an existing k8s secret
                key: .auth_token 
    - name: release-with-sbom
      dag:
        tasks:
          - name: build-image
            template: builder
          - name: generate-sbom
            dependencies: [build-image]
            template: sbom-generation
          - name: prepare-sbom-file
            template: sbom-file-preperation
            arguments:
              artifacts:
                - name: sbom
                  from: "{{tasks.generate-sbom.outputs.artifacts.sbom}}"
            dependencies: [generate-sbom]
          - name: parse-sbom-output
            template: sbom-output-parsing
            arguments: 
              artifacts:
                - name: sbom
                  from: "{{tasks.generate-sbom.outputs.artifacts.sbom}}"
            dependencies: [generate-sbom]
          - name: create-release-event
            template: release-event
            arguments:
              artifacts:
                - name: sbom
                  from: "{{tasks.generate-sbom.outputs.artifacts.sbom}}"
              parameters:
                - name: sbom_attrs
                  value: '{"name": "ACME Roadrunner Detector 2013 Coyote Edition SP1", "description": "v4.1.5 Release - ACME Roadrunner Detector 2013 Coyote Edition SP1", "hash": "a314fc2dc663ae7a6b6bc6787594057396e6b3f569cd50fd5ddb4d1bbafd2b6a", "version": "v4.1.5", "author": "The ACME Corporation", "supplier": "Coyote Services, Inc.", "uuid": "com.acme.rrd2013-ce-sp1-v4-1-5-0"}'
                - name: attachments
                  value: '["/tmp/{{workflow.parameters.sbom_version}}_sbom.json"]'
                - name: latest_sbom
                  value: '{"name": "ACME Roadrunner Detector 2013 Coyote Edition SP1", "description": "v4.1.5 Release - ACME Roadrunner Detector 2013 Coyote Edition SP1", "hash": "a314fc2dc663ae7a6b6bc6787594057396e6b3f569cd50fd5ddb4d1bbafd2b6a", "version": "v4.1.5", "author": "The ACME Corporation", "supplier": "Coyote Services, Inc.", "uuid": "com.acme.rrd2013-ce-sp1-v4-1-5-0"}'
                - name: custom_attrs
                  value: "{}"
                - name: custom_asset_attrs
                  value: "{}"
            dependencies: [parse-sbom-output, prepare-sbom-file]
          - name: publish-image
            template: builder
            dependencies: [create-release-event] 
